In [1]:
import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt
import zipfile

In [2]:
with zipfile.ZipFile("onlineretail.zip","r") as zip_file:
    zip_file.extractall()

In [3]:
df = pd.read_csv("OnlineRetail.csv", encoding = 'ISO-8859-1')

In [4]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [5]:
df.info() # shows number of entries in each column that are not null

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [6]:
#shows number of columns that have null values 
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
df["Description"] = df["Description"].fillna("No Description Provided")

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  541909 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [9]:
df = df.dropna()

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  str
 1   StockCode    406829 non-null  str
 2   Description  406829 non-null  str
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  str
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 27.9 MB

In [11]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [12]:
df["CustomerID"] = df["CustomerID"].astype("str")

In [13]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID         str
Country            str
dtype: object

In [14]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [15]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID                str
Country                   str
dtype: object

In [16]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [17]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID                str
Country                   str
dtype: object

In [19]:
df.to_csv("OnlineRetail-cleaned.csv", index=False)

In [ ]:
#Creating DB in postgresql
#psql -U postgres -p 8084 -d retail_db

In [ ]:
#How much total revenue did the business generate?
#total revenue = Sum (unitprice * quantity)
#SELECT SUM(unitprice*quantity) as TotalRevenue from retail_table
        sum
-------------------
 8300065.768524028
#total revenue grouped by year 
#SELECT extract(year from invoicedate) as year from retail_table;
#SELECT extract(year from invoicedate) as year,, SUM(quantity*unitprice) as sales_year from retail_table GROUP BY year ORDER BY year;
 year |    sales_year
------+-------------------
 2010 | 554604.0180353969
 2011 | 7745461.750488631
#total revenue grouped by month
#SELECT extract(month from invoicedate) as month from retail_table;
#SELECT extract(month from invoicedate) as month, extract(year from invoicedate) as year, SUM(quantity*unitprice) as sales_month from retail_table GROUP BY month, year ORDER BY month, year;
 month | year |    sales_month
-------+------+--------------------
     1 | 2011 | 475074.37782397866
     2 | 2011 |  436546.1481234729
     3 | 2011 |  579964.6072563156
     4 | 2011 |  426047.8488044123
     5 | 2011 |  648251.0762795284
     6 | 2011 |  608013.1562257819
     7 | 2011 |  574238.4776982571
     8 | 2011 |  616367.9967772514
     9 | 2011 |  931440.3665459079
    10 | 2011 |  974603.5833194144
    11 | 2011 |  1132407.733088296
    12 | 2010 |  554604.0180353969
    12 | 2011 |  342506.3785460144
#Insights 
#Revenue increased substantially from 2010 to 2011, reflecting business growth. 
#Despite this, December 2011 underperformed relative to December 2010 and other months in 2011, while November 2011 recorded the highest sales. 
#This indicates a possible shift in peak seasonal demand from December to November.

In [ ]:
#Which products make the most revenue?
#SELECT description, SUM(quantity*unitprice) as Revenue from retail_table WHERE quantity > 0 GROUP BY description ORDER BY Revenue DESC LIMIT 10;
            description             |      revenue
------------------------------------+-------------------
 PAPER CRAFT , LITTLE BIRDIE        | 168469.5938205719
 REGENCY CAKESTAND 3 TIER           | 142592.9483652115
 WHITE HANGING HEART T-LIGHT HOLDER | 100448.1498529911
 JUMBO BAG RED RETROSPOT            | 85220.77838778496
 MEDIUM CERAMIC TOP STORAGE JAR     | 81416.72709751129

 POSTAGE                            |  77803.9600019455
 PARTY BUNTING                      | 68844.32943487167
 ASSORTED COLOUR BIRD ORNAMENT      |  56580.3418970108
 Manual                             |  53779.9300766103
 RABBIT NIGHT LIGHT                 | 51346.19873857498
(10 rows)

In [ ]:
#Which products are sold the most (volume)?
#SELECT description, SUM(quantity) as volume from retail_table GROUP BY description ORDER BY volume DESC LIMIT 10;
      description                   | volume
------------------------------------+--------
 WORLD WAR 2 GLIDERS ASSTD DESIGNS  |  53215
 JUMBO BAG RED RETROSPOT            |  45066
 ASSORTED COLOUR BIRD ORNAMENT      |  35314
 WHITE HANGING HEART T-LIGHT HOLDER |  34147
 PACK OF 72 RETROSPOT CAKE CASES    |  33409

 POPCORN HOLDER                     |  30504
 RABBIT NIGHT LIGHT                 |  27094
 MINI PAINT SET VINTAGE             |  25880
 PACK OF 12 LONDON TISSUES          |  25321
 PACK OF 60 PINK PAISLEY CAKE CASES |  24163
(10 rows)

In [ ]:
#Which products generate very low revenue?

#SELECT description, SUM(quantity*unitprice) as revenue from retail_table WHERE quantity > 0 GROUP BY description ORDER BY revenue LIMIT 10 ;

             description             |       revenue
-------------------------------------+----------------------
 PADS TO MATCH ALL CUSHIONS          | 0.003000000142492354
 HEN HOUSE W CHICK IN NEST           |  0.41999998688697815
 SET 12 COLOURING PENCILS DOILEY     |   0.6499999761581421
 VINTAGE BLUE TINSEL REEL            |   0.8399999737739563
 PURPLE FRANGIPANI HAIRCLIP          |   0.8500000238418579
 PINK CRYSTAL GUITAR PHONE CHARM     |   0.8500000238418579
 HAPPY BIRTHDAY CARD TEDDY/CAKE      |    0.949999988079071
 CAT WITH SUNGLASSES BLANK CARD      |    0.949999988079071
 60 GOLD AND SILVER FAIRY CAKE CASES |    1.100000023841858
 PACK 4 FLOWER/BUTTERFLY PATCHES     |                 1.25
(10 rows)

In [ ]:
'''A small group of products contributes significantly to overall revenue, indicating a concentration of sales among key items. 
Some of the top revenue-generating products, such as “JUMBO BAG RED RETROSPOT” and “WHITE HANGING HEART T-LIGHT HOLDER,” also appear among the highest in sales volume, suggesting that both high demand and consistent sales drive their performance. 

However, this pattern is not universal, as certain high-revenue products do not rank among the top in volume, indicating the presence of higher-priced items contributing disproportionately to revenue. 

On the other end, there is a long tail of products generating minimal revenue, highlighting a large number of low-performing or rarely purchased items.'''

In [ ]:
#Who are the most valuable customers?
SELECT customerid, SUM(quantity*unitprice) as revenue from retail_table where quantity > 0 and customerid is NOT NULL GROUP BY customerid ORDER BY revenue desc LIMIT 10;
 customerid |      revenue
------------+--------------------
      14646 |  280206.0194363296
      18102 |  259657.2984648943
      17450 | 194550.79095315933
      16446 | 168472.49382054806
      14911 | 143825.05934465677
      12415 | 124914.53013676405
      14156 |  117379.6295517683
      17511 |  91062.37977567315
      16029 |  81024.83962202072
      12346 |  77183.59716892242
(10 rows)

In [ ]:
#Which customers order frequently?
#SELECT DISTINCT COUNT(DISTINCT invoiceno) as Invoice, customerid FROM retail_table GROUP BY customerid ORDER BY Invoice desc LIMIT 10;
 invoice | customerid
---------+------------
     248 |      14911
     224 |      12748
     169 |      17841
     128 |      14606
     118 |      13089
     118 |      15311
      89 |      12971
      86 |      14527
      81 |      13408
      77 |      14646
(10 rows)

In [ ]:
#How much does a customer spend per order?
#SELECT DISTINCT COUNT(DISTINCT invoiceno) as Invoice, SUM(quantity*unitprice)/COUNT(DISTINCT invoiceno) as Total_spent_per_order,customerid FROM retail_table GROUP BY customerid ORDER BY TOTAL_spent_per_order desc LIMIT 10;
 invoice | total_spent_per_order | customerid
---------+-----------------------+------------
       1 |     6207.669989347458 |      12357
       4 |      5383.97495341301 |      15749
       1 |     4873.809997737408 |      12688
      26 |    4758.6711585750945 |      12415
       1 |     4366.780012488365 |      12752
       1 |     4314.719962120056 |      18251
      62 |     4136.104650976196 |      18102
       3 |     4131.233325799306 |      16000
       1 |     4008.619987696409 |      12378
       2 |    3914.9449820518494 |      12435

In [ ]:
#Do customers come back or buy once?
#SELECT DISTINCT COUNT(DISTINCT invoiceno) as number_order_per_customer,customerid FROM retail_table GROUP BY customerid ORDER BY number_order_per_Customer desc LIMIT 10;
 number_order_per_customer | customerid
---------------------------+------------
                       248 |      14911
                       224 |      12748
                       169 |      17841
                       128 |      14606
                       118 |      13089
                       118 |      15311
                        89 |      12971
                        86 |      14527
                        81 |      13408
                        77 |      14646
(10 rows)

In [ ]:
'''A small group of customers contributes a significant portion of total revenue, indicating strong revenue concentration among high-value customers. 

Customers such as 14646 and 18102 generate the highest revenue, but they are not always the most frequent buyers. For example, customer 14911 places the highest number of orders but does not rank at the top in total revenue, suggesting that frequent purchases do not always translate to the highest spending.

Additionally, customers with the highest average order value tend to have a low number of orders, indicating that some customers make large, infrequent purchases, while others contribute through consistent, smaller transactions.

Overall, the business relies on a mix of high-frequency customers and high-value customers, highlighting different customer behaviors that drive revenue.'''

In [ ]:
#Step 4: Country/Region Analysis
Which countries generate the most revenue?
#Select Country, SUM(quantity*unitprice) as revenue from retail_table WHERE quantity > 0 AND customerid is NOT NULL GROUP BY Country ORDER BY revenue desc LIMIT 10;
    country     |      revenue
----------------+--------------------
 United Kingdom |   7308391.50308007
 Netherlands    |  285446.3394470215
 EIRE           | 265545.89888782054
 Germany        |  228867.1388997957
 France         | 209024.04914559424
 Australia      |  138521.3100708723
 Spain          |   61577.1100255996
 Switzerland    |  56443.94986021519
 Belgium        | 41196.339941978455
 Sweden         |  38378.32967123389
(10 rows)

In [ ]:
#Where do most orders come from?
#Select Country, COUNT(DISTINCT invoiceno) as count_order from retail_table WHERE quantity > 0 AND customerid is NOT NULL GROUP BY Country ORDER BY count_order desc LIMIT 10;
    country     | count_order
----------------+-------------
 United Kingdom |       16649
 Germany        |         457
 France         |         389
 EIRE           |         260
 Belgium        |          98
 Netherlands    |          95
 Spain          |          90
 Portugal       |          57
 Australia      |          57
 Switzerland    |          51
(10 rows)

In [ ]:
#Which countries have higher spend per order?
#Select Country, SUM(unitprice*quantity)/COUNT(DISTINCT invoiceno) as max_revenue_per_order from retail_table WHERE quantity > 0 AND customerid is NOT NULL GROUP BY Country ORDER BY max_revenue_per_order desc LIMIT 10;
   country   | max_revenue_per_order
-------------+-----------------------
 Singapore   |    3039.8985712868825
 Netherlands |     3004.698309968647
 Australia   |    2430.1984222960054
 Japan       |    1969.2826247811317
 Lebanon     |     1693.879989862442
 Israel      |    1444.3379989862442
 Brazil      |    1143.5999937057495
 Switzerland |    1106.7441149061801
 Sweden      |    1066.0647130898303
 Denmark     |    1053.0744422392713
(10 rows)

In [1]:
#Is revenue concentrated in a few countries?
#Select Country, (SUM(quantity*unitprice)/10000000)*100 as revenue from retail_table WHERE quantity > 0 AND customerid is NOT NULL GROUP BY Country ORDER BY revenue desc LIMIT 10;
    country     |       revenue
----------------+---------------------
 United Kingdom |   73.08391503080071
 Netherlands    |   2.854463394470215
 EIRE           |  2.6554589888782054
 Germany        |  2.2886713889979573
 France         |  2.0902404914559423
 Australia      |   1.385213100708723
 Spain          |   0.615771100255996
 Switzerland    |  0.5644394986021518
 Belgium        | 0.41196339941978455
 Sweden         | 0.38378329671233896
(10 rows)

SyntaxError: invalid syntax (1011867681.py, line 2)

In [ ]:
'''Revenue is heavily concentrated in the United Kingdom, which contributes the vast majority of total sales (over 70%), indicating strong geographic dependency on a single market. 

Other countries such as the Netherlands, EIRE, Germany, and France contribute significantly less, each accounting for a small fraction of total revenue. This highlights a steep drop-off after the primary market.

Order volume follows a similar pattern, with the United Kingdom generating the highest number of orders by a large margin, reinforcing its dominance in both demand and revenue.

However, countries like Singapore, the Netherlands, and Australia exhibit significantly higher average order values despite lower order volumes. This suggests that while these markets are smaller, customers tend to make larger purchases per transaction.

Overall, the business is highly dependent on the UK market, with potential opportunities for growth in international markets that demonstrate high spending behavior but lower engagement.'''

In [ ]:
Business Summary 
'''
The overall sales performance shows a strong upward trend from 2010 to 2011, indicating business growth. However, the sales pattern is seasonal, with a noticeable shift in peak demand from December in 2010 to November in 2011, while December 2011 underperformed relative to both the previous year and other months.

Revenue is highly concentrated among a small set of products. Certain items, such as “JUMBO BAG RED RETROSPOT” and “WHITE HANGING HEART T-LIGHT HOLDER,” drive both high revenue and high sales volume, reflecting strong demand. At the same time, some products generate high revenue despite lower sales volume, indicating the influence of pricing. Additionally, there is a long tail of low-performing products contributing minimal revenue.

Customer analysis reveals that a small group of customers contributes a significant portion of total revenue. High-frequency customers are not always the highest spenders, highlighting different purchasing behaviors. Some customers make frequent, smaller purchases, while others contribute through fewer but higher-value transactions.

Geographically, the business is heavily dependent on the United Kingdom, which accounts for the majority of revenue and order volume. Other countries contribute significantly less, although markets such as the Netherlands and Australia show higher average order values despite lower transaction volumes.

Overall, the business demonstrates strong growth but relies heavily on a limited set of products, customers, and a single geographic region. This indicates potential risk due to concentration, while also highlighting opportunities to expand internationally and diversify both product performance and customer reach.

'''

In [ ]:
#converting retail_table to csv go to retail_db and do this to convert table to csv file
#```\copy (SELECT * from retail_table WHERE quantity > 0 and customerid is NOT NULL) TO 'C:/Users/goodw/AI-career-journey/data_analytics_projects/online_retail_dataset/retail_table.csv' DELIMITER ','  CSV HEADER```